name: Android Test and deploy

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Project ID
        run: WC_CLOUD_PROJECT_ID={{secrets.WC_CLOUD_PROJECT_ID}}
      - name: Unit tests
        run: ./gradlew sign:test
#  android_tests:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Instrumentation Tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew walletconnectv2:connectedAndroidTest